# Generated by Django 3.2 on 2023-06-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetatto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='painter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='image',
            name='painter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitetatto.painter'),
            preserve_default=False,
        ),
    ]
