# Generated by Django 3.2 on 2023-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Логи')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
        ),
    ]
